### ISSUE TITLE
Zeta-note `Client 1 quit with exit code 1 signal 0`

### ISSUE THREAD

**Issue by VolkovIlia** [neovim/nvim-lspconfig#1121]
- `nvim --version`: NVIM v0.5.0 Build type: Release LuaJIT 2.0.5
- nvim-lspconfig version(commit hash): 4bcc485
- What language server (If the problem is related to a specific language server): zeta-note
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): no
- Is the problem isolated to a particular language server: yes
- Operating system/version: linux / 5.13.6-artix1-1

### How to reproduce the problem from neovim startup

Try to install this server. Binary to path directory with name `zeta-note`, `.zeta.toml` to $HOME path. `zeta-note` is executable and has `user:wheel` permissions

### Actual behaviour

Lsp server not started with message: `Client 1 quit with exit code 1 and signal 0`

### Expected behaviour

Lsp server starts

### Minimal init.vim or init.lua and code sample

```
if !exists('g:lspconfig')
  finish
endif

lua << EOF
vim.lsp.set_log_level("debug")
EOF

lua << EOF
local nvim_lsp = require('lspconfig')
local protocol = require'vim.lsp.protocol'

-- Use an on_attach function to only map the following keys 
-- after the language server attaches to the current buffer
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  --Enable completion triggered by <c-x><c-o>
--  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }

  -- See `:help vim.lsp.*` for documentation on any of the below functions
  buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
  --buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  --buf_set_keymap('i', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  --buf_set_keymap('n', '<C-j>', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', '<S-C-j>', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)

  -- formatting
  if client.resolved_capabilities.document_formatting then
    vim.api.nvim_command [[augroup Format]]
    vim.api.nvim_command [[autocmd! * <buffer>]]
    vim.api.nvim_command [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_seq_sync()]]
    vim.api.nvim_command [[augroup END]]
  end

  require'completion'.on_attach(client, bufnr)

  --protocol.SymbolKind = { }
  protocol.CompletionItemKind = {
    '', -- Text
    '', -- Method
    '', -- Function
    '', -- Constructor
    '', -- Field
    '', -- Variable
    '', -- Class
    'ﰮ', -- Interface
    '', -- Module
    '', -- Property
    '', -- Unit
    '', -- Value
    '', -- Enum
    '', -- Keyword
    '﬌', -- Snippet
    '', -- Color
    '', -- File
    '', -- Reference
    '', -- Folder
    '', -- EnumMember
    '', -- Constant
    '', -- Struct
    '', -- Event
    '', -- Operator
    '', -- TypeParameter
  }
end

nvim_lsp.flow.setup {
on_attach = on_attach
}

nvim_lsp.pyright.setup{
on_attach = on_attach
}

nvim_lsp.zeta_note.setup {
on_attach = on_attach,
cmd = {'zeta-note'},
}

EOF

```

### Health check
<details>
<summary>Checkhealth result</summary>

</details>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyright: configuration checked.
  - INFO: zeta_note: configuration checked.
  - INFO: flow: configuration checked.
```

### LSP log

<details>
<summary>Log file</summary>

</details>

```

[ INFO ] 2021-08-02T19:17:29+0300 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:1214 ]	"exit_handler"	{}
[ INFO ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:316 ]	"Starting RPC client"	{  args = {},  cmd = "zeta-note",  extra = {}}
[ DEBUG ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:827 ]	"LSP[zeta_note]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false,      <metatable> = <1>{        __tostring = <function 1>      }    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = false,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      publishDiagnostics = {        relatedInformation = true,        tagSupport = {          valueSet = { 1, 2 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      rename = {        dynamicRegistration = false,        prepareSupport = true,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    window = {      showDocument = {        support = false,        <metatable> = <table 1>      },      showMessage = {        messageActionItem = {          additionalPropertiesSupport = false,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workDoneProgress = true,      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspaceEdit = {        resourceOperations = { "rename", "create", "delete" },        <metatable> = <table 1>      },      workspaceFolders = true,      <metatable> = <table 1>    }  },  clientInfo = {    name = "Neovim",    version = "0.5.0"  },  initializationOptions = vim.empty_dict(),  processId = 31577,  rootPath = "/home/volk",  rootUri = "file:///home/volk",  trace = "off",  workspaceFolders = { {      name = "/home/volk",      uri = "file:///home/volk"    } }}
[ DEBUG ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      window = {        showDocument = {          support = false,          <metatable> = <table 1>        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false,            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workDoneProgress = true,        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" },          <metatable> = <table 1>        },        workspaceFolders = true,        <metatable> = <table 1>      }    },    clientInfo = {      name = "Neovim",      version = "0.5.0"    },    initializationOptions = vim.empty_dict(),    processId = 31577,    rootPath = "/home/volk",    rootUri = "file:///home/volk",    trace = "off",    workspaceFolders = { {        name = "/home/volk",        uri = "file:///home/volk"      } }  }}
[ ERROR ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"zeta-note"	"stderr"	"\27[2mAug 02 19:17:43.838\27[0m \27[32m INFO\27[0m zeta_note: Starting zeta-note LSP server\n"
[ DEBUG ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      completionProvider = {        resolveProvider = true,        triggerCharacters = { ":", "@" }      },      definitionProvider = true,      documentSymbolProvider = true,      hoverProvider = true,      semanticTokensProvider = {        full = true,        legend = {          tokenModifiers = {},          tokenTypes = { "class", "property" }        },        range = true      },      textDocumentSync = 2,      workspaceSymbolProvider = true    },    serverInfo = {      name = "zeta-note"    }  }}
[ DEBUG ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:854 ]	"LSP[zeta_note]"	"server_capabilities"	{  completionProvider = {    resolveProvider = true,    triggerCharacters = { ":", "@" }  },  definitionProvider = true,  documentSymbolProvider = true,  hoverProvider = true,  semanticTokensProvider = {    full = true,    legend = {      tokenModifiers = {},      tokenTypes = { "class", "property" }    },    range = true  },  textDocumentSync = 2,  workspaceSymbolProvider = true}
[ INFO ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:855 ]	"LSP[zeta_note]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = false,    code_lens = false,    code_lens_resolve = false,    completion = true,    declaration = false,    document_formatting = false,    document_highlight = false,    document_range_formatting = false,    document_symbol = true,    execute_command = false,    find_references = false,    goto_definition = true,    hover = true,    implementation = false,    rename = false,    signature_help = false,    signature_help_trigger_characters = {},    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = true,    text_document_save_include_text = false,    text_document_will_save = false,    text_document_will_save_wait_until = false,    type_definition = false,    workspace_folder_properties = {      changeNotifications = false,      supported = false    },    workspace_symbol = true  }}
[ DEBUG ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "markdown",      text = "Some awesome text\n",      uri = "file:///home/volk/markdown%20test/test_text.md",      version = 0    }  }}
[ DEBUG ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:434 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 4,  params = {    diagnostics = {},    uri = "file:///home/volk/markdown%20test/test_text.md"  }}
[ ERROR ] 2021-08-02T19:17:43+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"zeta-note"	"stderr"	"\27[2mAug 02 19:17:43.844\27[0m \27[32m INFO\27[0m zeta_note::lsp::server: Starting zeta-note main loop at /home/volk\n"
[ ERROR ] 2021-08-02T19:17:44+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"zeta-note"	"stderr"	"thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: \"SendError(..)\"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.0/src/stdio.rs:29:37\nstack backtrace:\n"
[ ERROR ] 2021-08-02T19:17:44+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"zeta-note"	"stderr"	"Error: Permission denied (os error 13"
[ ERROR ] 2021-08-02T19:17:44+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"zeta-note"	"stderr"	")\n"

```

As I assume it is permissions problem, but I don't understand what exactly wrong.

**Comment by mjlbach** [comment]
The server is panicking, this seems like an upstream issue.

**Comment by mjlbach** [comment]
Please file an issue upstream.

**Comment by VolkovIlia** [comment]
> Please file an issue upstream.

Sorry, but don't understand the way of fixing this issue...??

**Comment by mjlbach** [comment]
You'll have to seek help from the language server author. All this repository does is sent initializationOptions and settings (via workspace/didChangeConfiguration) to the language server after starting it. The server itself is panicking:

```
[ ERROR ] 2021-08-02T19:17:44+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"zeta-note"	"stderr"	"thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: \"SendError(..)\"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.0/src/stdio.rs:29:37\nstack backtrace:\n"
[ ERROR ] 2021-08-02T19:17:44+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"zeta-note"	"stderr"	"Error: Permission denied (os error 13"
```

So file an issue with zeta-note.

**Comment by VolkovIlia** [comment]
Thx.
