### ISSUE TITLE
yaml language server is failing for version?

### ISSUE THREAD

**Issue by mosheavni** [neovim/nvim-lspconfig#1902]
### Description

yaml-language-server has suddenly stopped giving me schema completion options, so I turned on debug mode and saw this error:
```
[DEBUG][2022-05-14 02:42:00] .../vim/lsp/rpc.lua:454	"rpc.receive"	{  jsonrpc = "2.0",  method = "telemetry/event",  params = {    name = "yaml.validation.error",    properties = "Error: Expected '1.1', '1.2' or null as first argument, but found: undefined\n    at Document.setSchema (/Users/mavni/.local/share/nvim/lsp_servers/yaml/node_modules/yaml-language-server/node_modules/yaml/dist/doc/Document.js:273:23)\n    at new Document (/Users/mavni/.local/share/nvim/lsp_servers/yaml/node_modules/yaml-language-server/node_modules/yaml/dist/doc/Document.js:53:14)\n    at Object.composeDoc (/Users/mavni/.local/share/nvim/lsp_servers/yaml/node_modules/yaml-language-server/node_modules/yaml/dist/compose/compose-doc.js:10:17)\n    at Composer.next (/Users/mavni/.local/share/nvim/lsp_servers/yaml/node_modules/yaml-language-server/node_modules/yaml/dist/compose/composer.js:149:40)\n    at next (<anonymous>)\n    at Composer.compose (/Users/mavni/.local/share/nvim/lsp_servers/yaml/node_modules/yaml-language-server/node_modules/yaml/dist/compose/composer.js:131:25)\n    at compose.next (<anonymous>)\n    at Function.from (<anonymous>)\n    at Object.parse (/Users/mavni/.local/share/nvim/lsp_servers/yaml/node_modules/yaml-language-server/out/server/src/languageservice/parser/yamlParser07.js:45:28)\n    at YamlDocuments.ensureCache (/Users/mavni/.local/share/nvim/lsp_servers/yaml/node_modules/yaml-language-server/out/server/src/languageservice/parser/yaml-documents.js:224:40)",    type = "track"  }}

```

### Neovim version

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info

### Operating system and version

macOS 12.2.1

### Affected language servers

yamlls

### Steps to reproduce

1. `nvim -nu minimal_init.lua`
2. that's it, the log shows the error

### Actual behavior

described above

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end

    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.diagnostic.open_float()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.diagnostic.setloclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'yamlls'
  local cmd = { 'node', '/Users/mavni/Repos/yaml-language-server/out/server/src/server.js', '--stdio' }

  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
    settings = {
      trace = {
        server = "verbose"
      },
      completion = true,
      format = {
        enable = true
      },
      validate = true,
      schemaStore = {
        enable = true,
      },
      schemas = {
        kubernetes = '*'
      }
    }
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

https://gist.github.com/mosheavni/fd7756621b061709dd61046f50c19a89

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
