### ISSUE TITLE
LSP returns NIL workspace configuration response

### ISSUE THREAD

**Issue by implosivemosaic** [neovim/nvim-lspconfig#1968]
### Description

I've been trying to get the Astro LSP up and running but failing due to an empty configuration response. I can see a connected client but the LSP log is showing a `vim.NIL` response to the `workspace/configuration` request. This results in the Astro configuration manager throwing an error and prevents the language server integration from working with the client.

Here are some relevant lines of log output:
```
[DEBUG][2022-06-20 16:03:02] .../vim/lsp/rpc.lua:454    "rpc.receive"   {  id = 1,  jsonrpc = "2.0",  method = "workspace/configuration",  params = {    items = { {        scopeUri = "file:///Users/john/project/src/components/Author.astro",        section = "astro"      } }  }}
[TRACE][2022-06-20 16:03:02] .../lua/vim/lsp.lua:806    "server_request"        "workspace/configuration"       {  items = { {      scopeUri = "file:///Users/john/project/src/components/Author.astro",      section = "astro"    } }}
[TRACE][2022-06-20 16:03:02] .../lua/vim/lsp.lua:809    "server_request: found handler for"     "workspace/configuration"
[TRACE][2022-06-20 16:03:02] ...lsp/handlers.lua:487    "default_handler"       "workspace/configuration"       {  ctx = '{\n  client_id = 1,\n  method = "workspace/configuration"\n}',  result = {    items = { {        scopeUri = "file:///Users/john/project/src/components/Author.astro",        section = "astro"      } }  }}
[DEBUG][2022-06-20 16:03:02] .../vim/lsp/rpc.lua:464    "server_request: callback result"       {  result = { vim.NIL },  status = true}
[DEBUG][2022-06-20 16:03:02] .../vim/lsp/rpc.lua:347    "rpc.send"      {  id = 1,  jsonrpc = "2.0",  result = { vim.NIL }}
[ERROR][2022-06-20 16:03:02] .../vim/lsp/rpc.lua:420    "rpc"   "astro-ls"      "stderr"        "TypeError: Cannot read property 'typescript' of null\n    at ConfigManager.isEnabled (/opt/homebrew/lib/node_modules/@astrojs/language-server/dist/core/config/ConfigManager.js:146:92)\n    at async TypeScriptPlugin.featureEnabled (/opt/homebrew/lib/node_modules/@astrojs/language-server/dist/plugins/typescript/TypeScriptPlugin.js:141:18)\n    at async TypeScriptPlugin.getDiagnostics (/opt/homebrew/lib/node_modules/@astrojs/language-server/dist/plugins/typescript/TypeScriptPlugin.js:110:15)\n    at async PluginHost.tryExecutePlugin (/opt/homebrew/lib/node_modules/@astrojs/language-server/dist/plugins/PluginHost.js:174:20)\n    at async Promise.all (index 0)\n    at async PluginHost.getDiagnostics (/opt/homebrew/lib/node_modules/@astrojs/language-server/dist/plugins/PluginHost.js:66:38)\n    at async DiagnosticsManager.update (/opt/homebrew/lib/node_modules/@astrojs/language-server/dist/core/DiagnosticsManager.js:16:29)\n"
```

### Neovim version

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

c55e830

### Operating system and version

macOS 12.0.1

### Affected language servers

astro

### Steps to reproduce

1. `nvim -nu minimal_init.lua`
2. Open any astro file
3. Check the LSP log

### Actual behavior

Astro server throws an error.

### Expected behavior

No error thrown.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.cmd([[au BufRead,BufNewFile *.astro setfiletype astro]])
  vim.lsp.set_log_level 'trace'
  local nvim_lsp = require 'lspconfig'
  local configs = require 'lspconfig.configs'

  local name = "astro"
  require("lspconfig").astro.setup({})

  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

https://gist.github.com/implosivemosaic/a00c73456c0c2e4488208a4763e32f15

**Comment by justinmk** [comment]
Thanks for the well-crafted question, but we can't troubleshoot your setup or servers. This is just a repo for configs.

**Comment by implosivemosaic** [comment]
Oh I see! It looks like this may belong as a question over at neovim/neovim. Sorry about the distraction!
