### ISSUE TITLE
ESLint errors with 'No ESLint configuration found' because of package.json

### ISSUE THREAD

**Issue by mikehaertl** [neovim/nvim-lspconfig#2133]
### Description

If you open a js/ts file from a directory that has no eslint configuration in any of its parents but a `package.json` file and this file does not contain a `eslintConfig` a LSP server will still be started.

It then fails with an error message.

### Neovim version

NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/repos/github/neovim/build/config -I/home/repos/github/neovim/src -I/home/repos/github/neovim/.deps/usr/include -I/usr/include -I/home/repos/github/neovim/build/src/nvim/auto -I/home/repos/github/neovim/build/include
Übersetzt von mike@Nilar

Features: +acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

f8b3c240edad68bf549cae6b133cf2cac85554e8

### Operating system and version

Linux Mint 21

### Affected language servers

eslint

### Steps to reproduce

1. Create a js file and put a package.json in a parent directory.
2. Make sure there's no eslint config file in a parent
3. Open the js file with the default eslint setup

### Actual behavior

There's an error in the logs:

```
[ERROR][2022-09-13 13:52:32] .../vim/lsp/rpc.lua:420	"rpc"	"vscode-eslint-language-server"	"stderr"	"Uncaught exception received.
Error: No ESLint configuration found in /home/repos/local/node_modules/.pnpm/@urql+core@3.0.3_graphql@16.6.0/node_modules/@urql/core/dist/types/exchanges.
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/repos/local/node_modules/.pnpm/@eslint+eslintrc@1.3.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3962:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/repos/local/node_modules/.pnpm/@eslint+eslintrc@1.3.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3753:21)
    at CLIEngine.isPathIgnored ( /home/repos/local/node_modules/.pnpm/eslint@8.23.0/node_modules/eslint/lib/cli-engine/cli-engine.js :989:18)
    at ESLint.isPathIgnored (/home/repos/local/node_modules/.pnpm/eslint@8.23.0/node_modules/eslint/lib/eslint/eslint.js:678:26)
    at _callee6$ (/usr/local/lib/node_modules/vscode-langservers-extracted/lib/eslint-language-server/eslint.js:1407:50)
    at tryCatch (/usr/local/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/usr/local/lib/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/usr/local/lib/node_modules/vscode-langservers-extracted/lib/eslint-language-server/eslint.js:69:103)
    at _next (/usr/local/lib/node_modules/vscode-langservers-extracted/lib/eslint-language-server/eslint.js:71:194)
```

### Expected behavior

The `root_dir` handler should not only check if a `package.json` exists but also if that file contains a `eslintConfig` section.

https://github.com/neovim/nvim-lspconfig/blob/12735ee94a3eca96c4ebb799a62a0a7aa4733107/lua/lspconfig/server_configurations/eslint.lua#L54-L63

If no such section is found, no LSP server should be started.

### Minimal config

```Lua
The default eslint setup will do.
```

### LSP log

none available

**Comment by cpmsmith** [comment]
I'm seeing this too, and I think it's the reason I'm seeing these errors at the top of files:

```
Parsing error: The keyword 'const' is reserved
Parsing error: The keyword 'import' is reserved
```

…depending on which keyword I use first in that particular file. I think it's related because [ESLint defaults to ES5 syntax in absence of a config](https://stackoverflow.com/a/42706706/1612471)

**Comment by mikehaertl** [comment]
@cpmsmith You can try this workaround in your config

```lua
require'lspconfig'.eslint.setup {
  -- Copied from nvim-lspconfig/lua/lspconfig/server_conigurations/eslint.js
  root_dir = util.root_pattern(
   '.eslintrc',
   '.eslintrc.js',
   '.eslintrc.cjs',
   '.eslintrc.yaml',
   '.eslintrc.yml',
   '.eslintrc.json'
   -- Disabled to prevent "No ESLint configuration found" exceptions
   -- 'package.json',
 ), 
}
```

I never have eslint configuration in `package.json` so this works fine for me. If it doesn't help you probably see a different issue.

**Comment by glepnir** [comment]
can you test the #2208  ? thanks

**Comment by mikehaertl** [comment]
@glepnir Did some quick tests and #2208 really seems to fix the issue.

**Comment by glepnir** [comment]
oh glad to hear that. thanks for your test and reply :)

**Comment by VanillaBase1lb** [comment]
#2234 undid this fix and the error is back again.

**Comment by mikehaertl** [comment]
@VanillaBase1lb I can't confirm this. Actually #2234 fixed the logic to detect `eslintConfig` in `package.json` which didn't work correctly before. So maybe you have a broken `eslintConfig` in a `package.json` or something?

**Comment by brianmirandadev** [comment]
> @VanillaBase1lb I can't confirm this. Actually #2234 fixed the logic to detect `eslintConfig` in `package.json` which didn't work correctly before. So maybe you have a broken `eslintConfig` in a `package.json` or something?

I have the same issue, the error message doesn't go away if i don't have an eslint config on a separate file or inside the package.json

Am i obliged to always have a eslint configuration on a node project?

**Comment by mawkler** [comment]
I'm having the same issue. Whenever I open a node project without eslint set up I get the error `No ESLint configuration found` which is kinda annoying.

**Comment by mawkler** [comment]
I realize now that the reason I was seeing this message is because I had an `.eslintrc.json` in my home directory. If I remove it I no longer see the message.

**Comment by jayboss222** [comment]
> I realize now that the reason I was seeing this message is because I had an `.eslintrc.json` in my home directory. If I remove it I no longer see the message.

Agh this led me to check my home directory. Somehow I had the `eslint_d` binary sitting in `~/` directory, causing havoc in my lsp

**Comment by diegoulloao** [comment]
> > I realize now that the reason I was seeing this message is because I had an `.eslintrc.json` in my home directory. If I remove it I no longer see the message.
> 
> Agh this led me to check my home directory. Somehow I had the `eslint_d` binary sitting in `~/` directory, causing havoc in my lsp

I deleted it but is being created again and again every time I open the project...
Any solution for this?

**Comment by chintzyy** [comment]
@diegoulloao I'm experiencing the exact same issue 🤯

**Comment by diegoulloao** [comment]
> @diegoulloao I'm experiencing the exact same issue 🤯

actually I'm having this issue even when I'm using `oxlint` instead...

**Comment by tanmaymishu** [comment]
I have the same issue on a new Astro project:

<img width="836" alt="image" src="https://github.com/neovim/nvim-lspconfig/assets/13091708/1f0ba0af-9f0e-4d07-9c1c-198691f3005a">

**Comment by joelgrimberg** [comment]
Howcome is this one closed? I have the latest / gratest versions of my nvim plugins (incluing the nvim-lsp) but still I have this issue.

**Comment by diegoulloao** [comment]
@glepnir please reopen this issue.

**Comment by ruslankonev** [comment]
confirm issue, please reopen issue

**Comment by dzintars** [comment]
First try to debug eslint without Nvim. Go into your app directory and try to run `eslint_d --debug yourfile.js` and see, if that works. If that fails, then fix this issue first. Then check Nvim.

**Comment by justinmk** [comment]
The configs in this repo are provided as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#adding-a-server-to-lspconfig).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- a failing test case added to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
