### ISSUE TITLE
HTML or CSS LSP doesn't provide any autocompletion

### ISSUE THREAD

**Issue by lemonadeforlife** [neovim/nvim-lspconfig#3077]
### Description

Here is my LSP configuration, I believe it's the correct one:
```lua
        --Enable (broadcasting) snippet capability for completion
        local capabilities = vim.lsp.protocol.make_client_capabilities()
        capabilities.textDocument.completion.completionItem.snippetSupport = true
        lspconfig["html"].setup({
            capabilities = capabilities,
        })
        lspconfig["cssls"].setup({
            capabilities = capabilities,
        })
```

And I get this following error whenever I open any HTML or CSS file from **LspLog:**
```
[START][2023-11-21 16:15:03] LSP logging initiated
[ERROR][2023-11-21 16:15:03] .../vim/lsp/rpc.lua:734	"rpc"	"/home/nahian/.local/share/nvim/mason/bin/vscode-css-language-server"	"stderr"	"/home/nahian/.local/share/nvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-languageserver/lib/node/main.js:237\n        let counter = counters.get(message) ?? 0;\n                                             ^\n\nSyntaxError: Unexpected token '?'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/nahian/.local/share/nvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-languageserver/node.js:7:18)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n"
```
```
[START][2023-12-24 17:26:30] LSP logging initiated
[ERROR][2023-12-24 17:26:30] .../vim/lsp/rpc.lua:734	"rpc"	"/home/nahian/.local/share/nvim/mason/bin/vscode-html-language-server"	"stderr"	"/home/nahian/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-languageserver/lib/node/main.js:237\n        let counter = counters.get(message) ?? 0;\n                                             ^\n\nSyntaxError: Unexpected token '?'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/nahian/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-languageserver/node.js:7:18)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n"
```

I tried changing node version using nvm with both v20.11.1 & v21.7.1
Still getting the same error.

Current Result:
![image](https://github.com/neovim/nvim-lspconfig/assets/61580921/d4022b78-698d-4ac4-a7b5-770ddf9cfbad)

Here is the screenshot of my **LspInfo:**
![image](https://github.com/neovim/nvim-lspconfig/assets/61580921/9c4990e2-cc10-4df6-bd9e-ebf0ad031cbd)

**Comment by glepnir** [comment]
omnifunc ?

**Comment by lemonadeforlife** [comment]
> omnifunc ?

Actually, I just new Neovim & still learning about Neovim. I don't know what does that mean😅

**Comment by glepnir** [comment]
how do you trigger completion ? <C-x> <C-o> or just typing and which completion plugin you used.

**Comment by lemonadeforlife** [comment]
> how do you trigger completion ? or just typing and which completion plugin you used.

nvim-cmp

**Comment by glepnir** [comment]
ask in there and try follow the nvim-cmp setup . I guess it handle capabilities
