### ISSUE TITLE
Default html-lsp config causes errors when opening a html file with CSS <style> tag in it

### ISSUE THREAD

**Issue by adamrokickirns** [neovim/nvim-lspconfig#3393]
### Description

Opening a html file that contains embedded CSS in it throws the following error:

```
[ERROR][2024-10-23 01:56:57] ...lsp/handlers.lua:623	"Error while validating file:///home/user/code/test.html: Cannot read properties of null (reading 'validProperties')
TypeError: Cannot read properties of null (reading 'validProperties')
    at LintConfigurationSettings.getSetting (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lintRules.js:78:29)
    at new LintVisitor (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:53:41)
    at LintVisitor.entries (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:41:29)
    at CSSValidation.doValidation (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-css-languageservice/lib/umd/services/cssValidation.js:34:60)
    at _callee$ (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:53:69)
    at tryCatch (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.next (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:124:21)
    at asyncGeneratorStep (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:17:103)
    at _next (/home/user/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:19:194)"

```

**Comment by justinmk** [comment]
The configs in this repo are provided as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#adding-a-server-to-lspconfig).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- a failing test case added to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
