### ISSUE TITLE
Attempting to quit while using pyright hangs

### ISSUE THREAD

**Issue by eulertour** [neovim/nvim-lspconfig#947]
- `nvim --version`:
```
 ~ nvim --version
NVIM v0.5.0-dev+1362-g3cd688ff7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az50-56

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
- nvim-lsp version(commit hash): 9b4c71f98130e850b6ebb2e78b0500de7f355b1a
- What language server (If the problem is related to a specific language server): pyright
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): Unknown
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): Unknown
- Is the problem isolated to a particular language server: yes AFAICT
- Operating system/version: Arch Linux

### How to reproduce the problem from neovim startup
Repeatedly edit and save a file then attempt to quit neovim.

https://user-images.githubusercontent.com/43117506/120103244-91327d80-c103-11eb-91af-ca0c0146ae1a.mp4

### Actual behaviour
Neovim hangs for several seconds, sometimes up to 30s.

### Expected behaviour
Neovim exits immediately.

### Minimal init.vim or init.lua and code sample

```
require("packer").startup(
    function(use)
        use "wbthomason/packer.nvim"
        use "neovim/nvim-lspconfig"
        vim.cmd("packadd nvim-lspconfig")
    end
)
require'lspconfig'.pyright.setup {}
```

### Health check
<details>
<summary>Checkhealth result</summary>

</details>
```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyright: configuration checked.
```

### LSP log

https://pastebin.com/TCEe2wM9
<details>
<summary>Log file</summary>
[ START ] 2021-05-30T04:50:34-0700 ] LSP logging initiated
[ ERROR ] 2021-05-30T04:50:34-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:34 efm-langserver: no configuration file\n2021/05/30 04:50:34 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-05-30T04:50:34-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:34 lint for LanguageID not supported: python\n"
[ WARN ] 2021-05-30T04:50:34-0700 ] ....aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ ERROR ] 2021-05-30T04:50:35-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:35 format succeeded\n"
[ ERROR ] 2021-05-30T04:50:35-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:35 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:50:36-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:36 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:50:37-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:37 format succeeded\n"
[ ERROR ] 2021-05-30T04:50:37-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:37 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:50:38-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:38 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:50:39-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:39 format succeeded\n"
[ ERROR ] 2021-05-30T04:50:39-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:39 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:50:39-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:39 lint for LanguageID not supported: python\n"
[ WARN ] 2021-05-30T04:50:40-0700 ] ....aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:404 ]	"stubPath /home/devneal/typings is not a valid directory."
[ ERROR ] 2021-05-30T04:50:40-0700 ] ....aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:402 ]	"Exception received when installing recursive file system watcher"
[ ERROR ] 2021-05-30T04:50:42-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:42 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:50:45-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:45 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:50:46-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:46 lint for LanguageID not supported: python\n2021/05/30 04:50:46 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:50:46-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:46 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:51:22-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:50:49 format succeeded\n"
[ ERROR ] 2021-05-30T04:51:22-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	'2021/05/30 04:51:22 jsonrpc2 handler: notification "$/cancelRequest" handling error: jsonrpc2: code -32601 message: method not supported: $/cancelRequest\n'
[ ERROR ] 2021-05-30T04:51:22-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:51:22 lint for LanguageID not supported: python\n"
[ ERROR ] 2021-05-30T04:51:48-0700 ] ..._nvim.aeJHnKz/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55f2ca]\n\ngoroutine 7 [running]:\ntime.(*Timer).Stop(...)\n\t/usr/lib/go/src/time/sleep.go:78\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handleShutdown(0xc000132000, 0x5efd10, 0xc000014100, 0xc000136000, 0xc0002b0640, 0x58ff60, 0xc00029e620, 0xc000127d60, 0x5455d4)\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handle_shutdown.go:10 +0x2a\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handle(0xc000132000, 0x5efd10, 0xc000014100, 0xc000136000, 0xc0002b0640, 0x0, 0x0, 0x0, 0x0)\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handler.go:559 +0x19c\ngithub.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc0000104d0, 0x5efd10, 0xc000014100, 0xc000136000, 0xc0002b0640)\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/handler_with_error.go:21 +0x72\ngithub.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc000136000, 0x5efd10, 0xc000014100)\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:522 +0x57e\ncreated by github.com/sourcegraph/jsonrpc2.NewConn\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:334 +0x1d5\n"
[ START ] 2021-05-30T04:52:09-0700 ] LSP logging initiated
[ START ] 2021-05-30T04:53:06-0700 ] LSP logging initiated
[ ERROR ] 2021-05-30T04:53:06-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:06 efm-langserver: no configuration file\n2021/05/30 04:53:06 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-05-30T04:53:06-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:06 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:10-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:10 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:10-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:10 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:10-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:10 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:11-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:11 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:14-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:14 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:14-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:14 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:15-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:15 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:17-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/05/30 04:53:17 lint for LanguageID not supported: lua\n"
[ ERROR ] 2021-05-30T04:53:17-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55f2ca]\n\ngoroutine 7 [running]:\ntime.(*Timer).Stop(...)\n\t/usr/lib/go/src/time/sleep.go:78\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handleShutdown(0xc000132000, 0x5efd10, 0xc000014100, 0xc000136000, 0xc0000a9270, 0x58ff60, 0xc0000995c0, 0xc000127d60, 0x5455d4)\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handle_shutdown.go:10 +0x2a\ngithub.com/mattn/efm-langserver/langserver.(*langHandler).handle(0xc000132000, 0x5efd10, 0xc000014100, 0xc000136000, 0xc0000a9270, 0x0, 0x0, 0x0, 0x0)\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/mattn/efm-langserver@v0.0.29/langserver/handler.go:559 +0x19c\n"
[ ERROR ] 2021-05-30T04:53:17-0700 ] ..._nvim.aWzBvv8/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/devneal/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc0000104d0, 0x5efd10, 0xc000014100, 0xc000136000, 0xc0000a9270)\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/handler_with_error.go:21 +0x72\ngithub.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc000136000, 0x5efd10, 0xc000014100)\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:522 +0x57e\ncreated by github.com/sourcegraph/jsonrpc2.NewConn\n\t/home/devneal/.local/share/nvim/lspinstall/efm/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:334 +0x1d5\n"
[ START ] 2021-05-30T04:53:28-0700 ] LSP logging initiated
[ START ] 2021-05-30T04:53:32-0700 ] LSP logging initiated
[ WARN ] 2021-05-30T04:53:32-0700 ] ....aYjJuKa/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ ERROR ] 2021-05-30T04:53:38-0700 ] ....aYjJuKa/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:402 ]	"stubPath /home/devneal/typings is not a valid directory."
[ ERROR ] 2021-05-30T04:53:38-0700 ] ....aYjJuKa/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:402 ]	"Exception received when installing recursive file system watcher"
[ START ] 2021-05-30T04:57:35-0700 ] LSP logging initiated
[ WARN ] 2021-05-30T04:57:35-0700 ] ....aqRl8fd/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ ERROR ] 2021-05-30T04:57:41-0700 ] ....aqRl8fd/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:402 ]	"stubPath /home/devneal/typings is not a valid directory."
[ ERROR ] 2021-05-30T04:57:41-0700 ] ....aqRl8fd/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:402 ]	"Exception received when installing recursive file system watcher"
</details>

**Comment by eulertour** [comment]
This turned out to be caused because pyright was searching through several large file trees in my home directory. I managed to fix the problem by adding a `pyrightconfig.json` that excluded those directories.
